name: docs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: set up mkdocs
        run: pip install mkdocs
      - name: deploy to github pages
        run: mkdocs gh-deploy --force --clean --verbose